---
title: "Untitled"
output: html_document
date: "2023-07-19"
---
```{r package}
library(TSclust)
library(cluster)
library(factoextra)
library(MASS)
```


```{r new1}
generate2 <- function(mu1,n,p,p1,p2,p3,p4,p5)
{
  
  Sigma1 <- matrix(0,p,p)
  for(i in 1:p1)
  {
    for(j in 1:p1)
    {
      Sigma1[i,j] <- 0.10^abs(i-j)
    }
  }
  for(i in (p1+1):p2)
  {
    for(j in (p1+1):p2)
    {
      Sigma1[i,j] <- 0.15^abs(i-j)
    }
  }
  for(i in (p2+1):p3)
  {
    for(j in (p2+1):p3)
    {
      Sigma1[i,j] <- 0.20^abs(i-j)
    }
  }
  for(i in (p3+1):p4)
  {
    for(j in (p3+1):p4)
    {
      Sigma1[i,j] <- 0.25^abs(i-j)
    }
  }
  for(i in (p4+1):p5)
  {
    for(j in (p4+1):p5)
    {
      Sigma1[i,j] <- 0.35^abs(i-j)
    }
  }
  
  
  X <- matrix(0,nrow=p,ncol=n)
  for(i in 1:n)
  {
    X[,i] <- mvrnorm(1,mu=mu1,Sigma=Sigma1)
  }
  return(X)
}


```

```{r new2}
newfunc51 <- function(n,p,p1,p2,p3,p4,p5,c,gamma,value,grpnew)
{
   gam <- gamma
   theta2 <- list()
   mat2 <- list()
   matfull3 <- function(n,prev)
{
  b <- 0
  x <- numeric()
  n1 <- which(grpnew==n)
  for(i in 1:(length(n1)-1))
  {
  
    a <- b+1
    
    b <- a+(length(n1)-i)-1
    
    x <- rbind(x,c(rep(0,i-1),rep(1,1),prev[a:b]))
  }
  x <- rbind(x,c(rep(0,length(n1)-1),rep(1,1)))
  return(x)
}
matfull4 <- function(n,prev)
{
  b <- 0
  x <- numeric()
  n1 <- which(grpnew==n)
  for(i in 1:(length(n1)-1))
  {
  
    a <- b+1
    
    b <- a+(length(n1)-i)-1
    
    x <- cbind(x,c(rep(0,i),prev[a:b]))
  }
  x <- cbind(x,c(rep(0,length(n1))))
  return(x)
}

   for(n in 1:c)
   {
     
      n2 <- which(grpnew==n)
      if(length(n2) != 1)
      {
        tol <- 1e-5
        distance <- 1 + tol
        iter <- 0 

        value1 <- t(value) 
        val <- value1[,n2]
        matfull <- function(prev)
  {
  b <- 0
  x <- numeric()
  for(i in 1:(ncol(val)-1))
  {
  
    a <- b+1
    
    b <- a+(ncol(val)-i)-1
    
    x <- rbind(x,c(rep(0,i-1),rep(1,1),prev[a:b]))
  }
  x <- rbind(x,c(rep(0,ncol(val)-1),rep(1,1)))
  return(x)
}
        Y1 <- numeric()
        current11 <- numeric()
for(i in 1:ncol(val))
{
  current11[i] <- 1/var(val[,i])   #initial value of sigma
  Y1 <- c(Y1,val[,i]*as.numeric(sqrt(current11[i])))
}
  
X1 <- numeric()
for(i in 1:ncol(val))
{
  for(j in 1:ncol(val))
  {
    if(i < j)
    {
      aer <- c(rep(0,(i-1)*nrow(val)),val[,j]*as.numeric(sqrt(current11[j])),
                 rep(0,(j-i-1)*nrow(val)),val[,i]*as.numeric(sqrt(current11[i])),
                 rep(0,(ncol(val)-j)*nrow(val)))
        X1 <- cbind(X1,aer)
    }
    else
    {
      X1 <- X1
    }
  }
}
  

theta41 <- theta3(Y1,X1,gamma=gam)   #initial value of theta
  
while(distance > tol)
  {
    iter <- iter + 1
  
    previous <- current11
    prev <- theta41
    
    matnew <- matfull(prev)
    
    be <- matrix(-1,nrow(matnew),ncol(matnew))
    for(i in 1:nrow(matnew))
    {
      for(j in 1:ncol(matnew))
      {
        if(i<j)
        {
          be[i,j] <- matnew[i,j]*as.numeric(sqrt(previous[j]/previous[i]))
        }
        else if(i > j)
        {
          be[i,j] <- matnew[j,i]*as.numeric(sqrt(previous[j]/previous[i]))
        }
        else
        {
          be[i,j] <- -1
        }
      }
    
    }
    
    ben <- t(-be)
    for(i in 1:nrow(be))
    {
      sum <- 0
      for(j in 1:ncol(be))
      {
        if(j != i)
        {
          sum = sum+be[i,j]%*%val[,j]
        }
        else
          sum = sum
      }
      current11[i] <- nrow(val)/(norm(val[,i] - sum,"2"))^2
    }
    Y1 <- numeric()
    for(i in 1:ncol(val))
    {
      Y1 <- c(Y1,val[,i]*as.numeric(sqrt(current11[i])))
    }
    X1 <- numeric()
    for(i in 1:ncol(val))
    {
      for(j in 1:ncol(val))
      {
        if(i < j)
        {
          aer <- c(rep(0,(i-1)*nrow(val)),val[,j]*as.numeric(sqrt(current11[j])),
                   rep(0,(j-i-1)*nrow(val)),val[,i]*as.numeric(sqrt(current11[i])),
                   rep(0,(ncol(val)-j)*nrow(val)))
          X1 <- cbind(X1,aer)
        }
        else
        {
          X1 <- X1
        }
      }
    }
    theta41 <- theta3(Y1,X1,gamma=gam)
    distance <- norm(previous - current11,"2")
}
theta2[[n]] <- theta41
mat2[[n]] <- matfull3(n,theta2[[n]]) + matfull4(n,theta2[[n]])
  }
else
{
  theta2[[n]] <- 1
  mat2[[n]] <- as.matrix(1)
}

}

n <- numeric()
new <- list()
sum <- rep(0,c)
for(i in 1:c)
{
  n[i] <- length(which(grpnew==i))
  sum[i] <- sum[i] + sum(n[1:i])
}
  

new[[1]] <- cbind(mat2[[1]],matrix(0,n[1],p-n[1]))
for(i in 2:c)
{
new[[i]] <- cbind(matrix(0,n[i],sum[i-1]),mat2[[i]],matrix(0,n[i],p-sum[i-1]-n[i]))
  
}
omega11 <- numeric()
for(i in 1:c)
{
  omega11 <- rbind(omega11,new[[i]])
}

new2 <- numeric()
for(i in 1:c)
{
  new2 <- c(new2,rep(median(theta2[[i]]),ncol(mat2[[i]])))
}
omega21 <- diag(new2)

new3 <- numeric()
for(i in 1:c)
{
  new3 <- c(new3,median(theta2[[i]]))
}
omega31 <- diag(new3)

Sigmaest <-solve(omega11)

alphaf <- ((t(matrix(1,nrow(value),1))%*%omega11%*%matrix(1,nrow(value),1)))/p
wgtf <- (omega11%*%matrix(1,nrow(value),1))
weif <- wgtf/(p*as.numeric(alphaf))
Sigma1 <- matrix(0,p,p)
  for(i in 1:p1)
  {
    for(j in 1:p1)
    {
      Sigma1[i,j] <- 0.10^abs(i-j)
    }
  }
  for(i in (p1+1):p2)
  {
    for(j in (p1+1):p2)
    {
      Sigma1[i,j] <- 0.15^abs(i-j)
    }
  }
  for(i in (p2+1):p3)
  {
    for(j in (p2+1):p3)
    {
      Sigma1[i,j] <- 0.20^abs(i-j)
    }
  }
  for(i in (p3+1):p4)
  {
    for(j in (p3+1):p4)
    {
      Sigma1[i,j] <- 0.25^abs(i-j)
    }
  }
  for(i in (p4+1):p5)
  {
    for(j in (p4+1):p5)
    {
      Sigma1[i,j] <- 0.30^abs(i-j)
    }
  }
  
  
omegat <- solve(Sigma1)
alphat <- ((t(matrix(1,nrow(value),1))%*%omegat%*%matrix(1,nrow(value),1)))/p
wgtft <- (omegat%*%matrix(1,nrow(value),1))
weift <- wgtft/(p*as.numeric(alphat)) 

varest1 <- abs(((t(weif)%*%Sigmaest%*%weif)/(t(weift)%*%Sigma1%*%weift))-1)
varest1
#risk estimation error
riskest1 <- abs(t(weif)%*%(Sigmaest-Sigma1)%*%weif)
riskest1
#portfolio weight estimation error
portest1 <- norm(weift-weif,"1")
portest1

return(c(varest1,  portest1, riskest1))
#print("2nd type" : varest2, riskest2, portest2)

}

newfunc61 <- function(n,p,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,value,gamma)
{
  
   gam <- gamma
   theta2 <- list()
   mat2 <- list()
   n2 <- 1:p
      
        tol <- 1e-5
        distance <- 1 + tol
        iter <- 0 

        value1 <- t(value) 
        val <- value1[,n2]
        matfull <- function(prev)
  {
  b <- 0
  x <- numeric()
  for(i in 1:(ncol(val)-1))
  {
  
    a <- b+1
    
    b <- a+(ncol(val)-i)-1
    
    x <- rbind(x,c(rep(0,i-1),rep(1,1),prev[a:b]))
  }
  x <- rbind(x,c(rep(0,ncol(val)-1),rep(1,1)))
  return(x)
}
        Y1 <- numeric()
        current11 <- numeric()
for(i in 1:ncol(val))
{
  current11[i] <- 1/var(val[,i])   #initial value of sigma
  Y1 <- c(Y1,val[,i]*as.numeric(sqrt(current11[i])))
}
  
X1 <- numeric()
for(i in 1:ncol(val))
{
  for(j in 1:ncol(val))
  {
    if(i < j)
    {
      aer <- c(rep(0,(i-1)*nrow(val)),val[,j]*as.numeric(sqrt(current11[j])),
                 rep(0,(j-i-1)*nrow(val)),val[,i]*as.numeric(sqrt(current11[i])),
                 rep(0,(ncol(val)-j)*nrow(val)))
        X1 <- cbind(X1,aer)
    }
    else
    {
      X1 <- X1
    }
  }
}
Y <- Y1
X <- X1

theta41 <- theta3(Y1,X1,gamma=gam)   #initial value of theta
  
while(distance > tol)
  {
    iter <- iter + 1
  
    previous <- current11
    prev <- theta41
    
    matnew <- matfull(prev)
    
    be <- matrix(-1,nrow(matnew),ncol(matnew))
    for(i in 1:nrow(matnew))
    {
      for(j in 1:ncol(matnew))
      {
        if(i<j)
        {
          be[i,j] <- matnew[i,j]*as.numeric(sqrt(previous[j]/previous[i]))
        }
        else if(i > j)
        {
          be[i,j] <- matnew[j,i]*as.numeric(sqrt(previous[j]/previous[i]))
        }
        else
        {
          be[i,j] <- -1
        }
      }
    
    }
    
    ben <- t(-be)
    for(i in 1:nrow(be))
    {
      sum <- 0
      for(j in 1:ncol(be))
      {
        if(j != i)
        {
          sum = sum+be[i,j]%*%val[,j]
        }
        else
          sum = sum
      }
      current11[i] <- nrow(val)/(norm(val[,i] - sum,"2"))^2
    }
    Y1 <- numeric()
    for(i in 1:ncol(val))
    {
      Y1 <- c(Y1,val[,i]*as.numeric(sqrt(current11[i])))
    }
    X1 <- numeric()
    for(i in 1:ncol(val))
    {
      for(j in 1:ncol(val))
      {
        if(i < j)
        {
          aer <- c(rep(0,(i-1)*nrow(val)),val[,j]*as.numeric(sqrt(current11[j])),
                   rep(0,(j-i-1)*nrow(val)),val[,i]*as.numeric(sqrt(current11[i])),
                   rep(0,(ncol(val)-j)*nrow(val)))
          X1 <- cbind(X1,aer)
        }
        else
        {
          X1 <- X1
        }
      }
    }
    theta41 <- theta3(Y1,X1,gamma=gam)
    distance <- norm(previous - current11,"2")
    distance
}
theta2 <- theta41
matfull3 <- function(prev)
{
  b <- 0
  x <- numeric()
  
  for(i in 1:(p-1))
  {
  
    a <- b+1
    
    b <- a+(p-i)-1
    
    x <- rbind(x,c(rep(0,i-1),rep(1,1),prev[a:b]))
  }
  x <- rbind(x,c(rep(0,p-1),rep(1,1)))
  return(x)
}
matfull4 <- function(prev)
{
  b <- 0
  x <- numeric()
  
  for(i in 1:(p-1))
  {
  
    a <- b+1
    
    b <- a+(p-i)-1
    
    x <- cbind(x,c(rep(0,i),prev[a:b]))
  }
  x <- cbind(x,c(rep(0,p)))
  return(x)
}

mat2 <- matfull3(theta2) + matfull4(theta2)



omega11 <- mat2



Sigmaest <-solve(omega11)

alphaf <- ((t(matrix(1,nrow(value),1))%*%omega11%*%matrix(1,nrow(value),1)))/p
wgtf <- (omega11%*%matrix(1,nrow(value),1))
weif <- wgtf/(p*as.numeric(alphaf))
Sigma1 <- matrix(0,p,p)
  for(i in 1:p1)
  {
    for(j in 1:p1)
    {
      Sigma1[i,j] <- 0.10^abs(i-j)
    }
  }
  for(i in (p1+1):p2)
  {
    for(j in (p1+1):p2)
    {
      Sigma1[i,j] <- 0.15^abs(i-j)
    }
  }
  for(i in (p2+1):p3)
  {
    for(j in (p2+1):p3)
    {
      Sigma1[i,j] <- 0.20^abs(i-j)
    }
  }
  for(i in (p3+1):p4)
  {
    for(j in (p3+1):p4)
    {
      Sigma1[i,j] <- 0.25^abs(i-j)
    }
  }
  for(i in (p4+1):p5)
  {
    for(j in (p4+1):p5)
    {
      Sigma1[i,j] <- 0.30^abs(i-j)
    }
  }
  
  
omegat <- solve(Sigma1)
alphat <- ((t(matrix(1,nrow(value),1))%*%omegat%*%matrix(1,nrow(value),1)))/p
wgtft <- (omegat%*%matrix(1,nrow(value),1))
weift <- wgtft/(p*as.numeric(alphat)) 


varest1 <- abs(((t(weif)%*%Sigmaest%*%weif)/(t(weift)%*%Sigma1%*%weift))-1)
varest1
#risk estimation error
riskest1 <- abs(t(weif)%*%(Sigmaest-Sigma1)%*%weif)
riskest1
#portfolio weight estimation error
portest1 <- norm(weift-weif,"1")
portest1

return(c(varest1,  portest1, riskest1))
#print("2nd type" : varest2, riskest2, portest2)


}
newfunc71 <- function(n,p,p1,p2,p3,p4,p5,c,gamma,value,grpnew)
{
   gam <- gamma
   theta2 <- list()
   mat2 <- list()
   matfull3 <- function(n,prev)
{
  b <- 0
  x <- numeric()
  n1 <- which(grpnew==n)
  for(i in 1:(length(n1)-1))
  {
  
    a <- b+1
    
    b <- a+(length(n1)-i)-1
    
    x <- rbind(x,c(rep(0,i-1),rep(1,1),prev[a:b]))
  }
  x <- rbind(x,c(rep(0,length(n1)-1),rep(1,1)))
  return(x)
}
matfull4 <- function(n,prev)
{
  b <- 0
  x <- numeric()
  n1 <- which(grpnew==n)
  for(i in 1:(length(n1)-1))
  {
  
    a <- b+1
    
    b <- a+(length(n1)-i)-1
    
    x <- cbind(x,c(rep(0,i),prev[a:b]))
  }
  x <- cbind(x,c(rep(0,length(n1))))
  return(x)
}

   for(n in 1:c)
   {
     
      n2 <- which(grpnew==n)
      if(length(n2) != 1)
      {
        tol <- 1e-5
        distance <- 1 + tol
        iter <- 0 

        value1 <- t(value) 
        val <- value1[,n2]
        matfull <- function(prev)
  {
  b <- 0
  x <- numeric()
  for(i in 1:(ncol(val)-1))
  {
  
    a <- b+1
    
    b <- a+(ncol(val)-i)-1
    
    x <- rbind(x,c(rep(0,i-1),rep(1,1),prev[a:b]))
  }
  x <- rbind(x,c(rep(0,ncol(val)-1),rep(1,1)))
  return(x)
}
        Y1 <- numeric()
        current11 <- numeric()
for(i in 1:ncol(val))
{
  current11[i] <- 1/var(val[,i])   #initial value of sigma
  Y1 <- c(Y1,val[,i]*as.numeric(sqrt(current11[i])))
}
  
X1 <- numeric()
for(i in 1:ncol(val))
{
  for(j in 1:ncol(val))
  {
    if(i < j)
    {
      aer <- c(rep(0,(i-1)*nrow(val)),val[,j]*as.numeric(sqrt(current11[j])),
                 rep(0,(j-i-1)*nrow(val)),val[,i]*as.numeric(sqrt(current11[i])),
                 rep(0,(ncol(val)-j)*nrow(val)))
        X1 <- cbind(X1,aer)
    }
    else
    {
      X1 <- X1
    }
  }
}
  

theta41 <- theta3(Y1,X1,gamma=gam)   #initial value of theta
  
while(distance > tol)
  {
    iter <- iter + 1
  
    previous <- current11
    prev <- theta41
    
    matnew <- matfull(prev)
    
    be <- matrix(-1,nrow(matnew),ncol(matnew))
    for(i in 1:nrow(matnew))
    {
      for(j in 1:ncol(matnew))
      {
        if(i<j)
        {
          be[i,j] <- matnew[i,j]*as.numeric(sqrt(previous[j]/previous[i]))
        }
        else if(i > j)
        {
          be[i,j] <- matnew[j,i]*as.numeric(sqrt(previous[j]/previous[i]))
        }
        else
        {
          be[i,j] <- -1
        }
      }
    
    }
    
    ben <- t(-be)
    for(i in 1:nrow(be))
    {
      sum <- 0
      for(j in 1:ncol(be))
      {
        if(j != i)
        {
          sum = sum+be[i,j]%*%val[,j]
        }
        else
          sum = sum
      }
      current11[i] <- nrow(val)/(norm(val[,i] - sum,"2"))^2
    }
    
    distance <- norm(previous - current11,"2")
}
Y1 <- numeric()
    for(i in 1:ncol(val))
    {
      Y1 <- c(Y1,val[,i]*as.numeric(sqrt(current11[i])))
    }
    X1 <- numeric()
    for(i in 1:ncol(val))
    {
      for(j in 1:ncol(val))
      {
        if(i < j)
        {
          aer <- c(rep(0,(i-1)*nrow(val)),val[,j]*as.numeric(sqrt(current11[j])),
                   rep(0,(j-i-1)*nrow(val)),val[,i]*as.numeric(sqrt(current11[i])),
                   rep(0,(ncol(val)-j)*nrow(val)))
          X1 <- cbind(X1,aer)
        }
        else
        {
          X1 <- X1
        }
      }
    }
    theta41 <- theta3(Y1,X1,gamma=gam)
theta2[[n]] <- theta41
mat2[[n]] <- matfull3(n,theta2[[n]]) + matfull4(n,theta2[[n]])
  }
else
{
  theta2[[n]] <- 1
  mat2[[n]] <- as.matrix(1)
}

}

n <- numeric()
new <- list()
sum <- rep(0,c)
for(i in 1:c)
{
  n[i] <- length(which(grpnew==i))
  sum[i] <- sum[i] + sum(n[1:i])
}
  

new[[1]] <- cbind(mat2[[1]],matrix(0,n[1],p-n[1]))
for(i in 2:c)
{
new[[i]] <- cbind(matrix(0,n[i],sum[i-1]),mat2[[i]],matrix(0,n[i],p-sum[i-1]-n[i]))
  
}
omega11 <- numeric()
for(i in 1:c)
{
  omega11 <- rbind(omega11,new[[i]])
}

new2 <- numeric()
for(i in 1:c)
{
  new2 <- c(new2,rep(median(theta2[[i]]),ncol(mat2[[i]])))
}
omega21 <- diag(new2)

new3 <- numeric()
for(i in 1:c)
{
  new3 <- c(new3,median(theta2[[i]]))
}
omega31 <- diag(new3)

Sigmaest <-solve(omega11)

alphaf <- ((t(matrix(1,nrow(value),1))%*%omega11%*%matrix(1,nrow(value),1)))/p
wgtf <- (omega11%*%matrix(1,nrow(value),1))
weif <- wgtf/(p*as.numeric(alphaf))
Sigma1 <- matrix(0,p,p)
  for(i in 1:p1)
  {
    for(j in 1:p1)
    {
      Sigma1[i,j] <- 0.10^abs(i-j)
    }
  }
  for(i in (p1+1):p2)
  {
    for(j in (p1+1):p2)
    {
      Sigma1[i,j] <- 0.15^abs(i-j)
    }
  }
  for(i in (p2+1):p3)
  {
    for(j in (p2+1):p3)
    {
      Sigma1[i,j] <- 0.20^abs(i-j)
    }
  }
  for(i in (p3+1):p4)
  {
    for(j in (p3+1):p4)
    {
      Sigma1[i,j] <- 0.25^abs(i-j)
    }
  }
  for(i in (p4+1):p5)
  {
    for(j in (p4+1):p5)
    {
      Sigma1[i,j] <- 0.30^abs(i-j)
    }
  }
  
  
omegat <- solve(Sigma1)
alphat <- ((t(matrix(1,nrow(value),1))%*%omegat%*%matrix(1,nrow(value),1)))/p
wgtft <- (omegat%*%matrix(1,nrow(value),1))
weift <- wgtft/(p*as.numeric(alphat)) 


varest1 <- abs(((t(weif)%*%Sigmaest%*%weif)/(t(weift)%*%Sigma1%*%weift))-1)
varest1
#risk estimation error
riskest1 <- abs(t(weif)%*%(Sigmaest-Sigma1)%*%weif)
riskest1
#portfolio weight estimation error
portest1 <- norm(weift-weif,"1")
portest1

return(c(varest1,  portest1, riskest1))
#print("2nd type" : varest2, riskest2, portest2)

}

newfunc81 <- function(n,p,p1,p2,p3,p4,p5,gamma,value)
{
  
   gam <- gamma
   theta2 <- list()
   mat2 <- list()
   n2 <- 1:p
      
        tol <- 1e-5
        distance <- 1 + tol
        iter <- 0 

        value1 <- t(value) 
        val <- value1[,n2]
        matfull <- function(prev)
  {
  b <- 0
  x <- numeric()
  for(i in 1:(ncol(val)-1))
  {
  
    a <- b+1
    
    b <- a+(ncol(val)-i)-1
    
    x <- rbind(x,c(rep(0,i-1),rep(1,1),prev[a:b]))
  }
  x <- rbind(x,c(rep(0,ncol(val)-1),rep(1,1)))
  return(x)
}
        Y1 <- numeric()
        current11 <- numeric()
for(i in 1:ncol(val))
{
  current11[i] <- 1/var(val[,i])   #initial value of sigma
  Y1 <- c(Y1,val[,i]*as.numeric(sqrt(current11[i])))
}
  
X1 <- numeric()
for(i in 1:ncol(val))
{
  for(j in 1:ncol(val))
  {
    if(i < j)
    {
      aer <- c(rep(0,(i-1)*nrow(val)),val[,j]*as.numeric(sqrt(current11[j])),
                 rep(0,(j-i-1)*nrow(val)),val[,i]*as.numeric(sqrt(current11[i])),
                 rep(0,(ncol(val)-j)*nrow(val)))
        X1 <- cbind(X1,aer)
    }
    else
    {
      X1 <- X1
    }
  }
}
  

theta41 <- theta3(Y1,X1,gamma=gam)   #initial value of theta
  
while(distance > tol)
  {
    iter <- iter + 1
  
    previous <- current11
    prev <- theta41
    
    matnew <- matfull(prev)
    
    be <- matrix(-1,nrow(matnew),ncol(matnew))
    for(i in 1:nrow(matnew))
    {
      for(j in 1:ncol(matnew))
      {
        if(i<j)
        {
          be[i,j] <- matnew[i,j]*as.numeric(sqrt(previous[j]/previous[i]))
        }
        else if(i > j)
        {
          be[i,j] <- matnew[j,i]*as.numeric(sqrt(previous[j]/previous[i]))
        }
        else
        {
          be[i,j] <- -1
        }
      }
    
    }
    
    ben <- t(-be)
    for(i in 1:nrow(be))
    {
      sum <- 0
      for(j in 1:ncol(be))
      {
        if(j != i)
        {
          sum = sum+be[i,j]%*%val[,j]
        }
        else
          sum = sum
      }
      current11[i] <- nrow(val)/(norm(val[,i] - sum,"2"))^2
    }

    distance <- norm(previous - current11,"2")
}
    Y1 <- numeric()
    for(i in 1:ncol(val))
    {
      Y1 <- c(Y1,val[,i]*as.numeric(sqrt(current11[i])))
    }
    X1 <- numeric()
    for(i in 1:ncol(val))
    {
      for(j in 1:ncol(val))
      {
        if(i < j)
        {
          aer <- c(rep(0,(i-1)*nrow(val)),val[,j]*as.numeric(sqrt(current11[j])),
                   rep(0,(j-i-1)*nrow(val)),val[,i]*as.numeric(sqrt(current11[i])),
                   rep(0,(ncol(val)-j)*nrow(val)))
          X1 <- cbind(X1,aer)
        }
        else
        {
          X1 <- X1
        }
      }
    }
    theta41 <- theta3(Y1,X1,gamma=gam)
theta2 <- theta41
theta2 <- theta
matfull3 <- function(prev)
{
  b <- 0
  x <- numeric()
  
  for(i in 1:(p-1))
  {
  
    a <- b+1
    
    b <- a+(p-i)-1
    
    x <- rbind(x,c(rep(0,i-1),rep(1,1),prev[a:b]))
  }
  x <- rbind(x,c(rep(0,p-1),rep(1,1)))
  return(x)
}
matfull4 <- function(prev)
{
  b <- 0
  x <- numeric()
  
  for(i in 1:(p-1))
  {
  
    a <- b+1
    
    b <- a+(p-i)-1
    
    x <- cbind(x,c(rep(0,i),prev[a:b]))
  }
  x <- cbind(x,c(rep(0,p)))
  return(x)
}

mat2 <- matfull3(theta2) + matfull4(theta2)



omega11 <- mat2



Sigmaest <-solve(omega11)

alphaf <- ((t(matrix(1,nrow(value),1))%*%omega11%*%matrix(1,nrow(value),1)))/p
wgtf <- (omega11%*%matrix(1,nrow(value),1))
weif <- wgtf/(p*as.numeric(alphaf))
Sigma1 <- matrix(0,p,p)
  for(i in 1:p1)
  {
    for(j in 1:p1)
    {
      Sigma1[i,j] <- 0.10^abs(i-j)
    }
  }
  for(i in (p1+1):p2)
  {
    for(j in (p1+1):p2)
    {
      Sigma1[i,j] <- 0.15^abs(i-j)
    }
  }
  for(i in (p2+1):p3)
  {
    for(j in (p2+1):p3)
    {
      Sigma1[i,j] <- 0.20^abs(i-j)
    }
  }
  for(i in (p3+1):p4)
  {
    for(j in (p3+1):p4)
    {
      Sigma1[i,j] <- 0.25^abs(i-j)
    }
  }
  for(i in (p4+1):p5)
  {
    for(j in (p4+1):p5)
    {
      Sigma1[i,j] <- 0.30^abs(i-j)
    }
  }
  
omegat <- solve(Sigma1)
alphat <- ((t(matrix(1,nrow(value),1))%*%omegat%*%matrix(1,nrow(value),1)))/p
wgtft <- (omegat%*%matrix(1,nrow(value),1))
weift <- wgtft/(p*as.numeric(alphat)) 



varest1 <- abs(((t(weif)%*%Sigmaest%*%weif)/(t(weift)%*%Sigma1%*%weift))-1)
varest1
#risk estimation error
riskest1 <- abs(t(weif)%*%(Sigmaest-Sigma1)%*%weif)
riskest1
#portfolio weight estimation error
portest1 <- norm(weift-weif,"1")
portest1

return(c(varest1,  portest1, riskest1))
#print("2nd type" : varest2, riskest2, portest2)

}
```

```{r new2}
n <- 100
p <- 30

f1 <- matrix(0,3,3)
f2 <- matrix(0,3,3)
gamma <- 50
for(i in 1:3)
  {
    mu <- rep(0,p)
    value <- generate2(mu,n,p,6,12,18,24,30)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 6)
    
    f1[i,]<-newfunc51(n,p,6,12,18,24,30,c=6,gamma=50,value=value,grpnew=grpnew)
    f2[i,] <- newfunc61(n,p,6,12,18,24,30,value=value,gamma = 50)
}
f3 <- colMeans(f1)
f4 <- colMeans(f2)

b11 <- newfunc51(n,p,3,6,9,12,15,18,21,24,27,30,c=3,gamma=50,value=value,grpnew=grpnew)

b12 <- newfunc61(n,p,3,6,9,12,15,18,21,24,27,30,gamma=50)

```

```{r new3}
n <- 300
p <- 30

f1 <- matrix(0,3,3)
f2 <- matrix(0,3,3)
gamma <- 50
for(i in 1:3)
  {
    mu <- rep(0,p)
    value <- generate2(mu,n,p,6,12,18,24,30)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 6)
    
    f1[i,]<-newfunc51(n,p,6,12,18,24,30,c=6,gamma=50,value=value,grpnew=grpnew)
    f2[i,] <- newfunc61(n,p,6,12,18,24,30,value=value,gamma = 50)
}
f3 <- colMeans(f1)
f4 <- colMeans(f2)

b21 <- newfunc51(n,p,3,6,9,12,15,18,21,24,27,30,c=3,gamma=50,value=value,grpnew=grpnew)

b22 <- newfunc61(n,p,3,6,9,12,15,18,21,24,27,30,gamma=50)

```

```{r new4}
n <- 500
p <- 30

f1 <- matrix(0,3,3)
f2 <- matrix(0,3,3)
gamma <- 50
for(i in 1:3)
{
    mu <- rep(0,p)
    value <- generate2(mu,n,p,6,12,18,24,30)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 6)
    
    f1[i,]<-newfunc51(n,p,6,12,18,24,30,c=6,gamma=50,value=value,grpnew=grpnew)
    f2[i,] <- newfunc61(n,p,6,12,18,24,30,value=value,gamma = 50)
}
f3 <- colMeans(f1)
f4 <- colMeans(f2)

b31 <- newfunc51(n,p,3,6,9,12,15,18,21,24,27,30,c=3,gamma=50,value=value,grpnew=grpnew)

b32 <- newfunc61(n,p,3,6,9,12,15,18,21,24,27,30,gamma=50)

```

```{r new4}
n <- 1000
p <- 30

f1 <- matrix(0,3,3)
f2 <- matrix(0,3,3)
gamma <- 50
for(i in 1:3)
{
    mu <- rep(0,p)
    value <- generate2(mu,n,p,6,12,18,24,30)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 6)
    
    f1[i,]<-newfunc51(n,p,6,12,18,24,30,c=6,gamma=50,value=value,grpnew=grpnew)
    f2[i,] <- newfunc61(n,p,6,12,18,24,30,value=value,gamma = 50)
}
f3 <- colMeans(f1)
f4 <- colMeans(f2)

b41 <- newfunc51(n,p,3,6,9,12,15,18,21,24,27,30,c=3,gamma=50,value=value,grpnew=grpnew)

b42 <- newfunc61(n,p,3,6,9,12,15,18,21,24,27,30,gamma=50)

```

```{r new5}
n <- 100
p <- 100

f1 <- matrix(0,10,3)
gamma <- 50
for(i in 1:10)
  {
    mu <- rep(0,p)
    value <- generate2(mu,n,p,20,40,60,80,100)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 20)
    
    f1[i,]<-newfunc71(n,p,20,40,60,80,100,c=20,gamma=50,value=value,grpnew=grpnew)
}
f <- colMeans(f1)
b51 <- newfunc71(n,p,10,20,30,40,50,60,70,80,90,100,c=12,gamma=50)

b52 <- newfunc81(n,p,10,20,30,40,50,60,70,80,90,100,gamma=50,value=value)

```

```{r new6}
n <- 300
p <- 100

f1 <- matrix(0,10,3)
gamma <- 50
for(i in 1:10)
  {
    mu <- rep(0,p)
    value <- generate2(mu,n,p,20,40,60,80,100)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 20)
    
    f1[i,]<-newfunc51(n,p,20,40,60,80,100,c=20,gamma=50,value=value,grpnew=grpnew)
}
f <- colMeans(f1)
b71 <- newfunc51(n,p,10,20,30,40,50,60,70,80,90,100,c,gamma=50)

b72 <- newfunc61(n,p,10,20,30,40,50,60,70,80,90,100,gamma=50)

```

```{r new6}
n <- 500
p <- 100

f1 <- matrix(0,10,3)
gamma <- 50
for(i in 1:10)
  {
    mu <- rep(0,p)
    value <- generate2(mu,n,p,20,40,60,80,100)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 20)
    
    f1[i,]<-newfunc51(n,p,20,40,60,80,100,c=20,gamma=50,value=value,grpnew=grpnew)
}
f <- colMeans(f1)
b71 <- newfunc51(n,p,10,20,30,40,50,60,70,80,90,100,c,gamma=50)

b72 <- newfunc61(n,p,10,20,30,40,50,60,70,80,90,100,gamma=50)

```

```{r new6}
n <- 1000
p <- 100

f1 <- matrix(0,10,3)
gamma <- 50
for(i in 1:10)
  {
    mu <- rep(0,p)
    value <- generate2(mu,n,p,20,40,60,80,100)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 20)
    
    f1[i,]<-newfunc51(n,p,20,40,60,80,100,c=20,gamma=50,value=value,grpnew=grpnew)
}
f <- colMeans(f1)
b71 <- newfunc51(n,p,10,20,30,40,50,60,70,80,90,100,c,gamma=50)

b72 <- newfunc61(n,p,10,20,30,40,50,60,70,80,90,100,gamma=50)

```

```{r new6}
n <- 100
p <- 500

f1 <- matrix(0,10,3)
gamma <- 50
for(i in 1:10)
  {
    mu <- rep(0,p)
    value <- generate2(mu,n,p,100,200,300,400,500)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 100)
    
    f1[i,]<-newfunc71(n,p,100,200,300,400,500,c=100,gamma=50,value=value,grpnew=grpnew)
}
f <- colMeans(f1)
b71 <- newfunc51(n,p,10,20,30,40,50,60,70,80,90,100,c,gamma=50)

b72 <- newfunc61(n,p,10,20,30,40,50,60,70,80,90,100,gamma=50)

```

```{r new6}
n <- 300
p <- 500

f1 <- matrix(0,5,3)
gamma <- 50
for(i in 1:5)
  {
    mu <- rep(0,p)
    value <- generate2(mu,n,p,100,200,300,400,500)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 100)
    
    f1[i,]<-newfunc71(n,p,100,200,300,400,500,c=100,gamma=50,value=value,grpnew=grpnew)
}
f <- colMeans(f1)
b71 <- newfunc51(n,p,10,20,30,40,50,60,70,80,90,100,c,gamma=50)

b72 <- newfunc61(n,p,10,20,30,40,50,60,70,80,90,100,gamma=50)

```

```{r new6}
n <- 500
p <- 500

f1 <- matrix(0,5,3)
gamma <- 50
for(i in 1:5)
  {
    mu <- rep(0,p)
    value <- generate2(mu,n,p,100,200,300,400,500)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 100)
    
    f1[i,]<-newfunc71(n,p,100,200,300,400,500,c=100,gamma=50,value=value,grpnew=grpnew)
}
f <- colMeans(f1)
b71 <- newfunc51(n,p,10,20,30,40,50,60,70,80,90,100,c,gamma=50)

b72 <- newfunc61(n,p,10,20,30,40,50,60,70,80,90,100,gamma=50)

```

```{r new6}
n <- 1000
p <- 500

f1 <- matrix(0,5,3)
gamma <- 50
for(i in 1:5)
  {
    mu <- rep(0,p)
    value <- generate2(mu,n,p,100,200,300,400,500)
    distnew <- diss(value,METHOD="PACF")     
    hcnew <- hclust(distnew)
    grpnew <- cutree(hcnew, k = 100)
    
    f1[i,]<-newfunc71(n,p,100,200,300,400,500,c=100,gamma=50,value=value,grpnew=grpnew)
}
f <- colMeans(f1)
b71 <- newfunc51(n,p,10,20,30,40,50,60,70,80,90,100,c,gamma=50)

b72 <- newfunc61(n,p,10,20,30,40,50,60,70,80,90,100,gamma=50)

```